name: NBA Data Update

on:
  schedule:
    - cron: '0 13 * * *' # 7:00 AM MX aproximadamente
  workflow_dispatch: # Permite ejecutarlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main # Forzamos que baje la última versión de la rama principal

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          

      - name: Install dependencies
        run: |
          pip install requests python-dotenv supabase

      - name: 1. Update Raw Stats
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          SPORT_DATA_IO_KEY: ${{ secrets.SPORT_DATA_IO_KEY }}
        run: python stats_feeder.py

      - name: 2. Refresh Team Indices
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: python data_refresher.py

      - name: 3. Generate Daily Predictions
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          SPORT_DATA_IO_KEY: ${{ secrets.SPORT_DATA_IO_KEY }}
        run: python datawin_final.py
